# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'FlutterBoostDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterBoostDemo

  install_all_flutter_pods(flutter_application_path)


  target 'FlutterBoostDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterBoostDemoUITests' do
    # Pods for testing
  end

end
